name: Deploy Extension

on:
  push: 
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm ci

    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: master
        INITIAL_VERSION: 1.0.1
        DEFAULT_BUMP: patch

    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: "${{ steps.bump_version.outputs.new_tag }}"
        body: "${{ steps.build_changelog.outputs.changelog }}"
        draft: false

    - name: Update Change Log and npm version
      run: |
        echo -e "\n## ${{ steps.bump_version.outputs.new_tag }}\n${{ steps.build_changelog.outputs.changelog }}" >> CHANGELOG.md && npm --no-git-tag-version --no-commit-hooks version ${{ steps.bump_version.outputs.new_tag }}

    - name: Commit updated CHANGELOG and NPM Version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ github.event.release.target_commitish }}
        commit_message: "chore: Update the CHANGELOG and npm version for release ${{ steps.bump_version.outputs.new_tag }}"
        file_pattern: CHANGELOG.md

    - name: Publish VS Code Extension
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com