name: Deploy Extension

on:
  push: 
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm ci
    - name: Publish VS Code Extension
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com

  